name: .NET CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build (Release config)
      run: dotnet build --configuration Release

    - name: Test API (Release config)
      run: dotnet test Entwin.API.Tests/Entwin.API.Tests.csproj --configuration Release --verbosity normal

    # TODO: publish and deploy steps here (Azure)
